export const adjectives = [
  'Proven',
  'Disputed',
  'Irregular',
  'Diplomatic ',
  'Impartial',
  'Dynamic',
  'Laid Back',
  'Bilious',
  'Boorish',
  'Cerulean',
  'Contumacious',
  'Dilatory',
  'Efficacious',
  'Effulgent',
  'Equanimous',
  'Execrable',
  'Fastidious',
  'Fecund',
  'Garrulous',
  'Heuristic',
  'Histrionic',
  'Hubristic',
  'Insidious',
  'Inveterate',
  'Irksome',
  'Jocular',
  'Judicious',
  'Loquacious',
  'Meretricious',
  'Nefarious',
  'Parsimonious',
  'Pernicious',
  'Petulant',
  'Quiescent',
  'Rebarbative',
  'Redolent',
  'Risible',
  'Tenacious',
  'Verdant',
  'Voracious',
  'Zealous',
  'Yellow',
  'Orange',
  'Tempting',
  'Cheeky',
  'Crazy',
  'Spooky',
  'Fruity',
  'Candid',
  'Miraculous',
  'Whelming',
  'Under Whelming',
  'Over Whelming',
  'Average',
  'Spiteful',
  'Descriptive',
  'Flirtacious',
  'Alluring',
  'Rising',
  'Growing',
  'Dormant',
  'Bulging',
  'Throbbing',
  'Tingling',
  'Tactile',
  'Spongey',
  'Froggy',
  'Wobbly',
  'Fuzzy',
  'Shapely',
  'Sandy',
  'Dirty',
  'Eery',
  'Moist',
  'Wet',
  'Sticky',
  'Lanky',
  'Spanky',
  'Silly',
  'Little',
  'Rare',
  'Smelly',
  'Spicey',
  'Burny',
  'Tasty',
  'Forest Green',
  'Dark Blue',
  'Dead Salmon',
  'Mown Grass',
  'Mossy',
  'Slimey'
];

export const nouns = [
  'Collywobbles',
  'Bumfuzzles',
  'Donkey',
  'Banana',
  'Orange',
  'Lemon',
  'Package',
  'Speakers',
  'Sponge',
  'Beer Cans',
  'Froglegs',
  'Strawberries',
  'Saxaphone',
  'Needles',
  'Sand',
  'Dirt',
  'Bubblegum',
  'Pole',
  'Books',
  'Aubergine',
  'Wombat',
  'Kangaroo',
  'Rhino',
  'Mongoose',
  'Camel',
  'Temple',
  'Pyramid',
  ' Coffee',
  'Coffee cup',
  'Pereryv',
  'Burrito',
  'Noun',
  'Thing',
  'Cartwheel',
  'Jump',
  'Boots',
  'Ghosts',
  'Vampires',
  'Game',
  'Memories',
  'Symbol',
  'Word',
  'Idea',
  'Person',
  'Generalisation',
  'Anecdote',
  'Angst',
  'Anomaly',
  'Accolade',
  'Antidote',
  'Boondoggle',
  'Bourgeois',
  'Cacophony',
  'Charisma',
  'Deja Vu',
  'Euphemism',
  'Brexit Deal',
  'Handstand',
  'Ted Talk',
  'Fiasco',
  'Harbinger',
  'Mercenary',
  'BMW',
  'Mercedes',
  'Harley',
  'Boom Sound',
  'Paradox',
  'Spartan',
  'Hurdle',
  'Leap',
  'White Elephant',
  'Sunrise',
  'Sunset',
  'Tea',
  'Hot Water',
  'Cup',
  'Landfill',
  'Dungeon',
  'Master',
  'Debater',
  'Signal',
  'Space',
  'Moonlight',
  'Sound',
  'Nibble',
  'Catch Phrase',
  'Sandle',
  'Bandits',
  'Comeback',
  'Naartjie',
  'Vetkoek',
  'Koeksuster',
  'Cookie'
];
